 export interface Alarm {
    id?: number | null,
    alarmTypeId: number,
    alarmSeverity: number | string,
    alarmTypeName: string,
    objId: number,
    objName: string,
    objTypeId: number,
    equipmentId: number,
    equipmentName: string,
    equipmentSn: string,
    acked: boolean | number,
    ackUser: string,
    ackTime: Date | null,
    ackResult: number,
    ackDesc: string,
    alarmSource: string,
    longitude: number | null,
    latitude: number | null,
    cleared: boolean | number,
    clearUser: string,
    clearedTime: Date | null,
    alarmDatetime: Date | null,
    description: string
}